name: Python Tests on Multiple OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9, 3.10, 3.11]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        pytest src/testing/car_test.py
